bbs/urls.py
from django.urls import path
from . import views

app_name    = "bbs"
urlpatterns = [ 
    path('', views.index, name="index"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bbs.urls"), name="bbs"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bbs/models.py
from django.db import models

class Topic(models.Model):

    class Meta:
        db_table = "topic"

    comment = models.CharField(verbose_name="コメント",max_length=2000)
    img     = models.ImageField(verbose_name="イラスト",upload_to="img/")

    def __str__(self):
        return self.comment

bbs/forms.py
from django import forms

from .models import Topic

class TopicForm(forms.ModelForm):

    class Meta:
        model   = Topic
        fields  = [ "comment","img" ]

bbs/views.py
from django.shortcuts import render,redirect
from django.http.response import JsonResponse

from django.views import View
from .models import Topic
from .forms import TopicForm

class BbsView(View):

    def get(self, request, *args, **kwargs):

        topics  = Topic.objects.all()
        context = { "topics":topics }

        return render(request,"bbs/index.html",context)

    def post(self, request, *args, **kwargs):

        json    = { "error":True }

        form    = TopicForm(request.POST,request.FILES)

        if form.is_valid():
            print("OK")
            json["error"]   = False
            form.save()
        else:
            print("NG")


        return JsonResponse(json)

index   = BbsView.as_view()

templates/bbs/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<title>簡易掲示板</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <script src="{% static 'bbs/js/script.js' %}"></script>

    <script src="{% static 'bbs/js/draw.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bbs/css/style.css' %}">

</head>
<body>

    <h1 class="bg-primary text-white text-center">お絵かき掲示板</h1>

    <main class="container">
        <form id="form_area" action="{% url 'bbs:index' %}" method="POST">
            {% csrf_token %}
            <textarea class="form-control" name="comment"></textarea>
            <div class="my-2">
                <canvas id="canvas" class="canvas"  width="300px" height="300px"></canvas>
                <input id="canvas_clear" class="btn btn-danger" type="button" value="クリア">
            </div>
            <input id="submit" class="form-control" type="button" value="送信">
        </form>

        {% for topic in topics %}
        <div class="border">
            <div>{{ topic.comment }}</div>
            <div><img src="{{ topic.img.url }}" alt="投稿画像"></div>
        </div>
        {% endfor %}

    </main>
</body>
</html>